development:
  adapter: redis
  url: redis://redistogo:0a8391e4a5bc1ed208d5a181d7c1bf6c@hammerjaw.redistogo.com:11145

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:0a8391e4a5bc1ed208d5a181d7c1bf6c@hammerjaw.redistogo.com:11145
